<a href="https://colab.research.google.com/github/afeefafi246-pixel/my-studied/blob/main/DATA_SCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY(numerical python)
numpy is a python libarary used for working with arrays. used for mathematical operation
import: import numpy as np

In [ ]:
list=[1,2,3,4]
list2=[5,6,7,8]
result=list+list2
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
import numpy as np            #adding two list
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
result=arr1+arr2
print(result)

[ 6  8 10 12]


In [ ]:
arr1=np.array([10,20,30,40])    #slect a number in list
print(arr1[1])

20


In [ ]:
arr1=np.array([10,20,30,40,50,60,70,80])   #select a continues number in a list/ this array is 1D array
print(arr1[1:5])
print(arr1.ndim,"dimension")   #to find the dimension

[20 30 40 50]
1 dimension


In [ ]:
arr1=np.array([[1,2,3,4],        #2D array
               [6,7,8,9]])
print(arr1.ndim,"dimension")
print(arr1[1,1]) #to select a number in 2D array


2 dimension
7


In [ ]:
arr1=np.array([[[1,2,3,4],     #3D array
                [6,7,8,9],
                [3,4,5,6]]])
print(arr1.ndim,"dimension")
print(arr1[0,2,2])   #to select a number in a 3D array

3 dimension
5


In [ ]:
arr1=np.array([[[[1,2,3,4],     #4D array
                 [6,7,8,9],
                 [3,4,5,6],
                 [4,3,2,5]]]])
print(arr1.ndim,"dimension")
print(arr1[0,0,2,3])   #to select a number from 4D array

4 dimension
6


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8])
arr2=arr1.reshape(2,4)     #1D array is coverted to 2D array used reshape(a,b) a is how many rows and b is how maany elements in a row
print(arr1)
print(arr2)
print(arr2.shape) #to find the reshaped shape

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
a=()
a=np.zeros(5)  #zero array
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a=()
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:

a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.linspace(0,20,4)
print(a)

[ 0.          6.66666667 13.33333333 20.        ]


In [ ]:
#random
a=np.random.rand(12)
print(a)

[0.69729963 0.61889886 0.66507413 0.58606356 0.52685308 0.94971216
 0.76820566 0.73944532 0.29631795 0.35881033 0.3343297  0.32786817]


In [ ]:
import numpy as np
arr1=np.array([[[1,2,3,4],
                [5,6,7,8],
                [3,4,5,6]]])
print(arr1[0,1,3])

8


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,10,20,30,40,50,60,70,80])  #convert 1D array to 2D array used by reshape
arr2=arr1.reshape(2,8)
print(arr2)

[[ 1  2  3  4  5  6  7  8]
 [10 20 30 40 50 60 70 80]]


In [ ]:
import numpy as np
marks=np.array([78,92,65,88,90,45,72,55])
print(marks)
a=np.sum(marks)   #print sum
print(a)
b=np.average(marks)   #print average
print(b)
c=np.min(marks)    #print minimum
print(c)
d=np.max(marks)   #print maximum
print(d)
print(marks[marks>75])   #print above 75
print(marks[marks<50])   #print below 50
e=np.sort(marks)         #rearrange the marks with sort
print(e)

[78 92 65 88 90 45 72 55]
585
73.125
45
92
[78 92 88 90]
[45]
[45 55 65 72 78 88 90 92]


In [ ]:
import numpy as np
marks=np.array([78,92,65,88,90,45,72,55])
print("marks :",marks)
a=np.sum(marks)   #print sum
print("sum :",a)
b=np.average(marks)   #print average
print("average :",b)
c=np.min(marks)    #print minimum
print("minimum :",c)
d=np.max(marks)   #print maximum
print("maximum :",d)
print("above 75 :",marks[marks>75])   #print above 75
print("below 50 :",marks[marks<50])   #print below 50
e=np.sort(marks)         #rearrange the marks with sort
print("sort :",e)

marks : [78 92 65 88 90 45 72 55]
sum : 585
average : 73.125
minimum : 45
maximum : 92
above 75 : [78 92 88 90]
below 50 : [45]
sort : [45 55 65 72 78 88 90 92]


In [ ]:
a=np.arange(1,21)  #print a range of elements
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a=np.ones(4)
print(a)

[1. 1. 1. 1.]


In [ ]:
a=np.random.randint(1,100,6)  #random elements
print(a)
np.shape(a) #how many element

[ 2 93 16 80 89 81]


(6,)

In [ ]:
temp=np.array([32,35,40,28,42,33])
a=np.average(temp)
print(a)
b=np.min(temp)
print(b)
c=np.max(temp)
print(c)
temp[temp>38]=38
temp2=temp.reshape(2,3)
print(temp2)
print(temp2[0:1])
print(temp2[0,1])
print(temp2[1,1])


35.0
28
42
[[32 35 38]
 [28 38 33]]
[[32 35 38]]
35
38


In [ ]:
temp=np.array([32,35,40,28,42,33])
a=np.average(temp)
print(a)
b=np.min(temp)
print(b)
c=np.max(temp)
print(c)
temp[temp>38]=38
temp2=temp.reshape(2,3)
print(temp2)

print("first row :",temp2[0:1])
print("second column :",temp2[:, 1])


35.0
28
42
[[32 35 38]
 [28 38 33]]
first row : [[32 35 38]]
second column : [35 38]


In [ ]:
#(start,end,step)
a=np.array([10,20,30,40,50,60,70,80])
print(a[0],a[7])
print(a[0])
print(a[7])
print(a[1:8:3])
print(a[2:7])


10 80
10
80
[20 50 80]
[30 40 50 60 70]


In [ ]:
list=np.array([10,20,30,41,50,60,70,80])
print(list)
print(np.where(list%2==0))
(list%2==0)
print(list[list%2==0])
print(list[list%2==1])


[10 20 30 41 50 60 70 80]
(array([0, 1, 2, 4, 5, 6, 7]),)
[10 20 30 50 60 70 80]
[41]


PANDAS:--
panel data system.

PANDAS is an open source of python library used for data cleaning , data analysis, data manipulation and data visualization preparation .  Working with excel sheet or tabular formula data .

PANDAS DATA STRUCTURE:--
PANDAS as mainly two types (series and data frame)

IMPORT:-- import pandas as pd

SERIES:-- Series is an one dimensional labeled array

In [ ]:
import pandas as pd
marks=pd.Series([1,2,3,4,5]) #to used find the index
print(marks)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd
marks=pd.Series([10,20,30,40],index=["maths","physics","biology","chemistry"]) #it is change the index to usable for subject name
print(marks)

maths        10
physics      20
biology      30
chemistry    40
dtype: int64


In [ ]:
import pandas as pd
print("NAME        AGE")

info=pd.Series([18,19,18,20],index=["mehabs","afeef","aadhil","aravindh"])
print(info)

NAME        AGE
mehabs      18
afeef       19
aadhil      18
aravindh    20
dtype: int64


In [ ]:
import pandas as pd
print("NAME       CLASS")
course=pd.Series(["bca","bba","bcom"],index=["naja","afeef","aadhil"])
print(course)

NAME       CLASS
naja       bca
afeef      bba
aadhil    bcom
dtype: object


In [ ]:
import pandas as pd
print("NAME       CLASS")
course=pd.Series(["bca","bba","bcom"],index=["naja","afeef","aadhil"])
print(course)
print("course",course["naja"])

NAME       CLASS
naja       bca
afeef      bba
aadhil    bcom
dtype: object
course bca


1.what is numpy and pandas
2.why do you use numpy and pandas
3.what is series
4.what is the difference between list and numpy array
5.what is index in a slicing
6.create a numpy array contain numbers from 1 to 20
7.create a pandas series with doctors and department